pelikan-io/pelikan

Cargo.toml, README.md
Updates the readme and cargo manifest to reflect the URLs for the new fork.
=> Update readme and manifest to reflect new fork

src/protocol/memcache/src/request/mod.rs, src/protocol/memcache/src/response/values.rs
Improves usability of memcache protocol crate for use in clients by adding functions to construct requests.
=> feat: improve usability of memcache protocol

src/core/server/src/workers/mod.rs, src/protocol/http/src/error.rs, src/protocol/http/src/request.rs, src/protocol/resp/src/request/badd.rs, src/protocol/resp/src/request/hset.rs, src/protocol/resp/src/request/mod.rs, src/proxy/momento/src/main.rs, src/proxy/momento/src/protocol/resp/hexists.rs, src/proxy/momento/src/protocol/resp/hget.rs, src/proxy/momento/src/protocol/resp/hset.rs, src/storage/datapool/src/lib.rs, src/storage/seg/src/hashtable/mod.rs, src/storage/seg/src/item/header.rs, src/storage/seg/src/segments/builder.rs, src/storage/seg/src/segments/segments.rs, src/storage/seg/src/ttl_buckets/ttl_bucket.rs, src/storage/seg/src/ttl_buckets/ttl_buckets.rs
=> fix: address clippy warnings

src/protocol/resp/src/message/integer.rs, src/protocol/resp/src/request/hincrby.rs, src/protocol/resp/src/request/mod.rs, src/protocol/resp/src/util.rs, src/proxy/momento/src/frontend.rs, src/proxy/momento/src/protocol/resp/hincrby.rs, src/proxy/momento/src/protocol/resp/mod.rs
As in title. This PR:
- Adds HINCRBY support to the resp protocol crate 
- Adds HINCRBY support to the momento proxy
=> Implement support for the HINCRBY RESP command in Momento proxy

src/protocol/resp/src/request/mod.rs, src/protocol/resp/src/request/sadd.rs, src/proxy/momento/src/frontend.rs, src/proxy/momento/src/protocol/resp/mod.rs, src/proxy/momento/src/protocol/resp/sadd.rs
=> feat: Implement resp SADD command

Cargo.lock, src/proxy/momento/Cargo.toml
=> chore: update momento crate requirement to the latest version

src/protocol/resp/src/request/lindex.rs, src/protocol/resp/src/request/mod.rs, src/proxy/momento/src/frontend.rs, src/proxy/momento/src/protocol/resp/lindex.rs, src/proxy/momento/src/protocol/resp/mod.rs
=> feat: Implement the resp `LINDEX` command

src/protocol/resp/src/request/mod.rs, src/protocol/resp/src/request/srem.rs, src/proxy/momento/src/frontend.rs, src/proxy/momento/src/protocol/resp/mod.rs, src/proxy/momento/src/protocol/resp/srem.rs
=> feat: implement resp `SREM` command

src/protocol/resp/src/request/llen.rs, src/protocol/resp/src/request/mod.rs, src/proxy/momento/src/frontend.rs, src/proxy/momento/src/protocol/resp/llen.rs, src/proxy/momento/src/protocol/resp/mod.rs
=> feat: Implement resp `LLEN` command

src/protocol/resp/src/request/mod.rs, src/protocol/resp/src/request/sdiff.rs, src/proxy/momento/src/frontend.rs, src/proxy/momento/src/protocol/resp/mod.rs, src/proxy/momento/src/protocol/resp/sdiff.rs
=> feat: Implement resp `SDIFF` comand

src/protocol/resp/src/request/mod.rs
=> fix: issue #40 panic in RESP protocol parser

src/protocol/resp/src/request/mod.rs, src/protocol/resp/src/request/sunion.rs, src/proxy/momento/src/frontend.rs, src/proxy/momento/src/protocol/resp/mod.rs, src/proxy/momento/src/protocol/resp/sunion.rs
=> feat: Implement resp `SUNION` command

src/protocol/resp/src/request/mod.rs, src/protocol/resp/src/request/sinter.rs, src/proxy/momento/src/frontend.rs, src/proxy/momento/src/protocol/resp/mod.rs, src/proxy/momento/src/protocol/resp/sinter.rs
=> feat: Implement resp `SINTER` command

src/protocol/resp/src/request/mod.rs, src/protocol/resp/src/request/smembers.rs, src/proxy/momento/src/frontend.rs, src/proxy/momento/src/protocol/resp/mod.rs, src/proxy/momento/src/protocol/resp/smembers.rs
=> feat: Implement resp `SMEMBERS` command

Cargo.lock
This is currently blocking all commits.
=> Update tempfile to address vulnerability in remove_dir_all

Cargo.lock, src/proxy/momento/Cargo.toml, src/proxy/momento/src/admin.rs, src/proxy/momento/src/error.rs, src/proxy/momento/src/frontend.rs, src/proxy/momento/src/klog.rs, src/proxy/momento/src/main.rs, src/proxy/momento/src/protocol/memcache/get.rs, src/proxy/momento/src/protocol/memcache/set.rs, src/proxy/momento/src/protocol/resp/get.rs, src/proxy/momento/src/protocol/resp/hdel.rs, src/proxy/momento/src/protocol/resp/hexists.rs, src/proxy/momento/src/protocol/resp/hget.rs, src/proxy/momento/src/protocol/resp/hgetall.rs, src/proxy/momento/src/protocol/resp/hincrby.rs, src/proxy/momento/src/protocol/resp/hkeys.rs, src/proxy/momento/src/protocol/resp/hlen.rs, src/proxy/momento/src/protocol/resp/hmget.rs, src/proxy/momento/src/protocol/resp/hset.rs, src/proxy/momento/src/protocol/resp/hvals.rs, src/proxy/momento/src/protocol/resp/lindex.rs, src/proxy/momento/src/protocol/resp/llen.rs, src/proxy/momento/src/protocol/resp/mod.rs, src/proxy/momento/src/protocol/resp/set.rs, src/proxy/momento/src/protocol/resp/sismember.rs, src/proxy/momento/src/protocol/resp/smembers.rs
Update the `momento` crate to the latest version and improve error messages returned in both client responses and those used for logging. This can help improve experience when trying to debug issues.
=> feat: update momento client and improve error messages

src/protocol/resp/src/request/del.rs, src/protocol/resp/src/request/mod.rs
Adds the redis 'del' command to the resp protocol
=> feat: add redis 'del' command to resp protocol

Cargo.lock, src/proxy/momento/Cargo.toml, src/proxy/momento/src/main.rs, src/proxy/momento/src/protocol/memcache/get.rs, src/proxy/momento/src/protocol/resp/get.rs, src/proxy/momento/src/protocol/resp/hexists.rs, src/proxy/momento/src/protocol/resp/hget.rs, src/proxy/momento/src/protocol/resp/hgetall.rs, src/proxy/momento/src/protocol/resp/hkeys.rs, src/proxy/momento/src/protocol/resp/hlen.rs, src/proxy/momento/src/protocol/resp/hmget.rs, src/proxy/momento/src/protocol/resp/hvals.rs
Update the Momento client to the latest version so that the proxy is able to be used with the current version of the Momento service.
=> fix(momento-proxy): update momento client to latest version

Cargo.lock, src/net/Cargo.toml
Sets a crate-level version for pelikan-net
=> set version for pelikan-net

.github/workflows/cargo.yml, Cargo.toml
Update the pelikan-net version in the workspace root.
=> update pelikan-net dependency in workspace root
