pelikan-io/pelikan

Cargo.lock
Cargo.toml

Moves the rustcommon dependency from twitter/rustcommon to pelikan-io/rustcommon.

move rustcommon dependency to pelikan-io fork

---

Cargo.lock
Cargo.toml
src/protocol/resp/src/request/badd.rs
src/protocol/resp/src/request/set.rs
src/protocol/resp/src/util.rs

Fixes #3 by improving the utlity functions which we use to operate
on the array of tokens.
Previously, we were having to track our position in the token
stream but were mixing that with functions which removed tokens
from the stream.
This change makes all the utility functions act by attempting to
take a token from the front of the token stream. This makes the
parser more intuitive to write and less likely to have the same
class of bug.

bugfix for resp parser

---

Cargo.lock
src/proxy/momento/Cargo.toml
src/proxy/momento/src/main.rs

@brayniac this contains [Momento SDK update](https://github.com/momentohq/client-sdk-rust/releases/tag/v0.8.3) to tweak how we manage keep-alive setting for GRPC channels. This should resolve issue we were seeing with network errors from proxy after sitting idle for some time.

feat: bumps momento sdk to latest version for proxy

---

src/protocol/resp/src/request/badd.rs
src/protocol/resp/src/request/get.rs
src/protocol/resp/src/request/hdel.rs
src/protocol/resp/src/request/hexists.rs
src/protocol/resp/src/request/hget.rs
src/protocol/resp/src/request/hgetall.rs
src/protocol/resp/src/request/hkeys.rs
src/protocol/resp/src/request/hlen.rs
src/protocol/resp/src/request/hmget.rs
src/protocol/resp/src/request/hset.rs
src/protocol/resp/src/request/hvals.rs
src/protocol/resp/src/request/mod.rs
src/protocol/resp/src/request/set.rs
src/proxy/momento/src/protocol/resp/set.rs

Minor refactoring of the RESP protocol to make struct names more consistent with memcache protocol implementation.
Adds constructor methods for request types to make it usable from client code.

refactor resp protocol

---

README.md

Fixes badges and links in readme to reflect 'main' as the default branch.

docs: fix badges and links in readme

---

.github/actions/setup-protoc/action.yml
.github/workflows/cargo.yml
.github/workflows/fuzz.yml
Cargo.lock
src/config/src/momento_proxy.rs
src/proxy/momento/Cargo.toml
src/proxy/momento/src/main.rs
src/proxy/momento/src/protocol/memcache/set.rs
src/proxy/momento/src/protocol/resp/hincrby.rs
src/proxy/momento/src/protocol/resp/hmget.rs
src/proxy/momento/src/protocol/resp/hset.rs
src/proxy/momento/src/protocol/resp/set.rs

There's been a few changes in the momento crate's public API. This PR updates the proxy to make use of them.

chore: Update momento to v0.21.0

---

Cargo.lock
src/protocol/resp/src/request/mod.rs
src/proxy/momento/Cargo.toml
src/proxy/momento/src/error.rs
src/proxy/momento/src/frontend.rs
src/proxy/momento/src/main.rs
src/proxy/momento/src/protocol/resp/get.rs
src/proxy/momento/src/protocol/resp/hdel.rs
src/proxy/momento/src/protocol/resp/hincrby.rs
src/proxy/momento/src/protocol/resp/lindex.rs
src/proxy/momento/src/protocol/resp/llen.rs
src/proxy/momento/src/protocol/resp/mod.rs

The command handling in the momento proxy has a _lot_ of duplicated code (about 60% of lines for each new command are copy-paste). By refactoring things I have moved the common code up one level so that common error handling and metrics work no longer needs to be copy-pasted in to each new function.
The detailed changes are as follows:
- Introduce a new error type that covers all error cases encountered in the resp client.
- Move common metric updates up into `handle_resp_client` using the error type above to figure out what needs to be updated.
- Update `GET` and `HDEL` to take advantage of this as an example of the benefits.
I haven't updated all the commands yet, that will happen once I've finished up what I need to do for momento and have some time to cover the remaining commands.

chore: refactor momento frontend to reduce code duplication

---

src/protocol/resp/src/request/mod.rs

Right now, adding a new resp command involves touching a number of different places within `mod.rs`. None of these really introduce more information. By wrapping this all up in a macro we can make sure that updating it is easy and also that we don't end up forgetting a case where it would have mattered.

feat: use a macro to avoid all the duplication for `resp::Request`

---

src/entrystore/src/seg/resp.rs
src/protocol/resp/src/request/mod.rs
src/protocol/resp/src/request/sdiff.rs
src/protocol/resp/src/request/set.rs
src/protocol/resp/src/request/sinter.rs
src/protocol/resp/src/request/sunion.rs
src/proxy/momento/src/frontend.rs
src/proxy/momento/src/protocol/resp/lpop.rs
src/proxy/momento/src/protocol/resp/rpop.rs
src/server/rds/benches/benchmark.rs
src/server/rds/src/main.rs
src/server/rds/tests/common.rs
src/server/rds/tests/integration.rs
src/server/rds/tests/integration_multi.rs

We have a bunch of these. All this PR does is run `cargo clippy --fix` over the codebase.

chore: fix clippy warnings

---

.github/workflows/cargo.yml

These tests don't actually cause errors if they fail so we might as well just remove them.

chore: Remove CI smoketests

---

.github/actions/setup-rust/action.yml
.github/workflows/cargo.yml

Turns out this actually doesn't work but was masked because we were setting `RUSTFLAGS` via an environment variable in the jobs.

chore: Don't use LLD for CI

---

Dockerfile

If we are only running the release binary of `momento_proxy` in this `Dockerfile` then we can speed up the docker build by only building that one package

chore: only build momento_proxy in Dockerfile

---

.dockerignore

This shouldn't improve anything in a CI-context i.e. any time you're cloning the repository fresh and running docker commands inside.
However, with local development, we are currently sending all of `target` in the Docker "build context" which, on my machine is 18GB and dramatically slows down the Docker build loop.

chore: add .dockerignore to speed up local builds

---

Dockerfile

Fix #75 
Before I added this line, the Docker image failed to build. After I added it, I get a built docker image
I also changed the `apt-get update` and subsequent `apt-get install` to be a single-line docker statement in https://github.com/pelikan-io/pelikan/pull/76/commits/f8e090960fca6b4775f6b28d50820bda90eebc7a
This has a performance benefit by minimizing the number of layers as well as forcing `apt-get update` to be run again uncached if the list of packages to be installed changes (reference [1 ](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/)and [2](https://stackoverflow.com/questions/56329971/putting-run-commands-in-one-line-make-build-faster))

fix: install `protobuf-compiler` before using it in Dockerfile

---

.github/workflows/cargo.yml

The existing one keeps running into 429 errors. This PR takes a different approach and just caches the built binary.

Use an alternate install action to install cargo-audit

---

src/protocol/ping/Cargo.toml
src/protocol/ping/src/lib.rs
src/protocol/ping/src/ping/wire/mod.rs

Changes the ping protocol stats to properly feature gate them. Previously, the stats were being registered even when the client and/or server features were not selected.

fix: properly feature gate ping protocol stats

---

Cargo.lock
Cargo.toml
src/storage/datatier/Cargo.toml
src/storage/datatier/src/lib.rs
src/storage/seg/Cargo.toml
src/storage/seg/src/builder.rs
src/storage/seg/src/eviction/mod.rs
src/storage/seg/src/lib.rs
src/storage/seg/src/seg.rs
src/storage/seg/src/segments/header.rs
src/storage/seg/src/segments/segments.rs
src/storage/seg/src/ttl_buckets/ttl_bucket.rs

Rename the `datapool` crate to `datatier` and prepare to publish.
Reduce the un-published dependencies of the `seg` crate. Remove usage of `recent()` times in favor of `now()`.

feat: prepare datatier for publish

---

src/protocol/resp/src/lib.rs
src/protocol/resp/src/message/bulk_string.rs
src/protocol/resp/src/message/simple_string.rs

Provides access to the contents of bulk and simple string messgaes.
Adds re-export of `Compose` and `Parse` traits for convenience.

feat: provide access to resp string message content

---

src/protocol/resp/src/message/array.rs

Fixes a bug in the resp protocol implementation for composing array messages into the wire format. Fixes the incorrect prefix character for non-null array messages and ensures correct unit tests are present and passing.

fix: resp protocol bug for array message compose

---

src/protocol/resp/src/message/array.rs

Adds a `len` function for array message types in the resp protocol.

feat: add len for array messages in resp protocol

---

src/protocol/memcache/src/lib.rs
src/protocol/memcache/src/request/mod.rs

Export the TimeTime in the memcache protocol crate so that clients can construct requests with TTLs.

feat: export TimeType in memcache protocol

---

src/protocol/resp/src/message/array.rs

Adds an iterator for resp array messages so that clients can iterate through all messages in an array message.

feat: add iterator for resp array messages

---

Cargo.lock
src/common/Cargo.toml
src/common/src/ssl.rs
src/core/admin/Cargo.toml
src/core/admin/src/lib.rs
src/core/proxy/Cargo.toml
src/core/proxy/src/backend.rs
src/core/proxy/src/frontend.rs
src/core/proxy/src/lib.rs
src/core/proxy/src/listener.rs
src/core/server/Cargo.toml
src/core/server/src/lib.rs
src/core/server/src/listener.rs
src/core/server/src/workers/multi.rs
src/core/server/src/workers/single.rs
src/core/server/src/workers/storage.rs
src/net/Cargo.toml
src/proxy/momento/Cargo.toml
src/proxy/momento/src/frontend.rs
src/proxy/momento/src/listener.rs
src/proxy/momento/src/main.rs
src/proxy/momento/src/protocol/memcache/delete.rs
src/proxy/momento/src/protocol/memcache/get.rs
src/proxy/momento/src/protocol/memcache/set.rs
src/session/Cargo.toml
src/session/src/lib.rs

Renames the `net` crate to `pelikan-net` to prepare to publish it.

prepare pelikan-net for publish

---

Cargo.toml
src/common/Cargo.toml
src/core/admin/Cargo.toml
src/core/proxy/Cargo.toml
src/core/server/Cargo.toml
src/proxy/momento/Cargo.toml
src/session/Cargo.toml

Sets the pelikan-net dependency version at the workspace level and moves all dependencies to use the workspace dependency.

use versioned pelikan-net crate

---

Cargo.lock
Cargo.toml
src/config/Cargo.toml
src/config/src/proxy.rs

Drops support for resolving backend servers using zookeeper.
The zookeeper dependency is extremely dated and appears to be abandoned. Since we're not actively using this functionality, it's better to remove it for the time being.

drop zookeeper support for proxy

---

Cargo.lock
Cargo.toml
src/common/src/expiry.rs
src/common/src/lib.rs
src/common/src/time.rs
src/core/proxy/src/lib.rs
src/protocol/admin/Cargo.toml
src/protocol/common/Cargo.toml
src/protocol/memcache/Cargo.toml
src/protocol/memcache/src/request/mod.rs
src/protocol/ping/Cargo.toml
src/proxy/momento/src/admin.rs
src/server/pingserver/Cargo.toml
src/server/rds/Cargo.toml
src/server/segcache/Cargo.toml
src/session/Cargo.toml
src/session/src/lib.rs
src/storage/bloom/Cargo.toml
src/storage/datatier/src/lib.rs
src/storage/segcache/Cargo.toml
src/storage/segcache/src/lib.rs

Addresses all of the cargo audit errors and warnings by updating dependencies.
Removes public export of clocksource types from the common lib and moves to directly depending on clocksource where necessary.

address cargo audit errors and warnings

---

src/session/Cargo.toml

Removes the transitive dependency on boringssl by restricting the set of features enabled on direct dependencies for session crate.

session: remove transisitive dependency on boringssl

---

Cargo.lock
Cargo.toml
src/common/Cargo.toml
src/core/proxy/Cargo.toml
src/core/server/Cargo.toml
src/net/Cargo.toml
src/net/src/lib.rs
src/net/src/listener.rs
src/net/src/metrics.rs
src/net/src/stream.rs
src/net/src/tcp.rs
src/net/src/tls_tcp/boringssl.rs
src/net/src/tls_tcp/openssl.rs
src/proxy/momento/Cargo.toml
src/proxy/ping/Cargo.toml
src/server/pingserver/Cargo.toml
src/server/rds/Cargo.toml
src/server/segcache/Cargo.toml

Changes the way metrics are included in pelikan-net, moving them behind a feature flag to make them opt-in.

pelikan-net: make metrics opt-in

---

src/proxy/momento/src/protocol/memcache/set.rs

I was seeing a 0 % hit rate when testing against Momento because the items were expiring immediately due to wrong ttl.

fix: treat memcached request ttl as seconds

---

src/proxy/momento/src/listener.rs
src/proxy/momento/src/main.rs

connections are pooled per configured cache, and reused by each
frontend memcached connection.
MOMENTO_CONNECTIONS_PER_CACHE defaults to 4, but you can set other
values if you want more connections.
In this way a memcached protocol client that recreates connections
rapidly will reuse the more expensive tls connections to momento.

Connection pooling on momento proxy

---

src/protocol/memcache/src/text/response/get.rs

After refactoring to support the memcached binary protocol, GET misses in text mode were being rendered as `NOT_FOUND\r\n` (via `Response::NotFound`), but per the ASCII spec they must emit `END\r\n` (an empty value set). This patch:
- In `TextProtocol::compose_get_response`, intercepts `Response::NotFound` and replaces it with a zero-length `Values` so that `compose()` writes exactly `END\r\n`.
- Leaves the binary branch untouched: GET misses still serialize as the correct `KEY_NOT_FOUND` status frame.
The text protocol never uses `NOT_FOUND` for GET; that token is only for operations like `delete` or `cas`. ASCII clients (telnet, spymemcached in text mode, etc.) expect `END` to terminate a miss, so returning `NOT_FOUND` was breaking them.
- Added unit tests verifying that a text-mode GET …

fix(protocol-memcache): emit END on GET misses instead of NOT_FOUND

---

.github/workflows/fuzz.yml

Fixes ci fuzz test workflow (broken by #153) by removing the thrift protocol test from the workflow.

fix ci fuzz test workflow
